// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadItem(arg1:string):Promise<void>;

export function GetConnected():Promise<boolean>;

export function GetFiles():Promise<{[key: string]: any}>;

export function GetListener():Promise<string>;

export function IsDownloading():Promise<string>;

export function KillAgent():Promise<void>;

export function PressedItem(arg1:string):Promise<any>;
