// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadItem(arg1) {
  return window['go']['main']['App']['DownloadItem'](arg1);
}

export function GetConnected() {
  return window['go']['main']['App']['GetConnected']();
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function GetListener() {
  return window['go']['main']['App']['GetListener']();
}

export function IsDownloading() {
  return window['go']['main']['App']['IsDownloading']();
}

export function KillAgent() {
  return window['go']['main']['App']['KillAgent']();
}

export function PressedItem(arg1) {
  return window['go']['main']['App']['PressedItem'](arg1);
}
